db: logistics
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
  connection-timeout: 60000
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  #  redis:
  #    host: localhost
  #    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.107.242:3306/logistics-prod?characterEncoding=UTF-8&useSSL=false
    #    url: jdbc:mysql://192.168.56.102:3306/logistics-prod?characterEncoding=UTF-8&useSSL=false
    username: logistics
    #    username: root
    password: Dongyue@123
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
#    password: 123456
logistics:
  base:
    url: "localhost:8888/api/v1/"
