db: logistics
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  #  redis:
  #    host: localhost
  #    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://47.105.107.242:3306/logistics-prod?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://192.168.56.102:3306/logistics-prod?characterEncoding=UTF-8&useSSL=false
    #    username: logistics
    username: root
    #    password: Dongyue@123
    password: 123456
logging:
  path: ./logs
  level:
    com.abc.chenzeshenga.logistics.mapper: debug
