db: logistics
server:
  port: 8888
  servlet:
    context-path: /api/v1
    session:
      cookie:
        name: BIUSID
  connection-timeout: 60000
spring:
  profiles:
    active: dev
    include: druid,mybatisplus,shiro
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.33.48:3306/logistics?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: logistics
    password: Dongyue@123
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
logistics:
  base:
    url: "localhost:8888/api/v1/"
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true